server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  type-aliases-package: com.my.springcloud.pojo  # 搜索指定包别名
  global-config:
    db-config:
      table-prefix: tb_  #全局的表名前缀。要求 表名前缀 + 实体类名 应该等于 表名称
      id-type: auto # 全局的主键生成策略。auto表示数据库主键自增
logging:
  config: classpath:log/logback-spring.xml
